# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0.xci
# IP: The module: 'cnn_bd_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0.xci
# IP: The module: 'cnn_bd_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/cnn_test/cnn_test.srcs/sources_1/bd/cnn_bd/ip/cnn_bd_rst_ps7_0_100M_0/cnn_bd_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
