# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/total_1/total_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==total_1 || ORIG_REF_NAME==total_1} -quiet] -quiet

# IP: bd/total_1/ip/total_1_total_0_0/total_1_total_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==total_1_total_0_0 || ORIG_REF_NAME==total_1_total_0_0} -quiet] -quiet

# IP: bd/total_1/ip/total_1_processing_system7_0_0/total_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==total_1_processing_system7_0_0 || ORIG_REF_NAME==total_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/total_1/ip/total_1_ps7_0_axi_periph_0/total_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==total_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==total_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/total_1/ip/total_1_rst_ps7_0_100M_0/total_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==total_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==total_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/total_1/ip/total_1_auto_pc_0/total_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==total_1_auto_pc_0 || ORIG_REF_NAME==total_1_auto_pc_0} -quiet] -quiet

# XDC: bd/total_1/total_1_ooc.xdc
