set_property SRC_FILE_INFO {cfile:C:/Users/xb2m8/Desktop/2019_FPGA_Design_Group3/Lab03/Hash_func/pynq-z2_v1.0.xdc rfile:../../../pynq-z2_v1.0.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M20   IOSTANDARD LVCMOS33 } [get_ports { sw_tri_i[0] }]; #IO_L7N_T1_AD2N_35 Sch=sw[0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS33 } [get_ports { sw_tri_i[1] }]; #IO_L7P_T1_AD2P_35 Sch=sw[1]
