# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/lab5_total/lab5_total.srcs/sources_1/bd/total_1/ip/total_1_processing_system7_0_0/total_1_processing_system7_0_0.xci
# IP: The module: 'total_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/lab5_total/lab5_total.srcs/sources_1/bd/total_1/ip/total_1_processing_system7_0_0/total_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'total_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado/lab5_total/lab5_total.srcs/sources_1/bd/total_1/ip/total_1_processing_system7_0_0/total_1_processing_system7_0_0.xci
# IP: The module: 'total_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/lab5_total/lab5_total.srcs/sources_1/bd/total_1/ip/total_1_processing_system7_0_0/total_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'total_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
